application: xiyuan5hu
version: 1
runtime: python
api_version: 1

handlers:
- url: /misc
  static_dir: misc

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: bootstrap.py
